// src/db/schema.ts
// Trade Insight Daily — Complete Drizzle ORM Schema
// Compatible with: Auth.js v5 (@auth/drizzle-adapter), Next.js 15, PostgreSQL (Neon)
//
// FK TYPE CONTRACT (Bug #11 Prevention):
//   users.id        → text  ∴ userId  in posts / subscriptions / payments / savedPosts = text
//   assets.id       → serial (int) ∴ assetId in posts = integer
//   subscriptions.id → serial (int) ∴ subscriptionId in payments = integer
//   posts.id        → serial (int) ∴ postId in savedPosts = integer

import {
  pgTable,
  pgEnum,
  text,
  boolean,
  timestamp,
  integer,
  serial,
  decimal,
  primaryKey,
  index,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";
import type { AdapterAccount } from "@auth/core/adapters";

// ═══════════════════════════════════════════════════════════════════════════════
// §1 — ENUMS
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Platform role — used to gate admin panel DB queries.
 * Note: Admin panel *login* uses a separate HMAC cookie system (not this role).
 * This role is for identifying admin users at the data layer.
 */
export const userRoleEnum = pgEnum("user_role", ["user", "admin"]);

/**
 * Multi-gateway payment providers.
 * Each provider has its own webhook handler under /api/webhooks/{provider}/route.ts
 * and its own server action under /actions/payments/{provider}.actions.ts
 */
export const paymentProviderEnum = pgEnum("payment_provider", [
  "stripe",  // Primary: Cards, Apple Pay, Google Pay — global
  "paypal",  // Alternative: PayPal Wallet — NA, EU, SEA
  "crypto",  // Web3: On-chain payments — DeFi community
  "bkash",   // Local: Mobile Money — Bangladesh / South Asia (60M+ users)
]);

/**
 * Subscription lifecycle states.
 * Mirrors Stripe's status vocabulary — other gateways are mapped to these same states
 * in their respective webhook handlers for a unified status model.
 */
export const subscriptionStatusEnum = pgEnum("subscription_status", [
  "active",             // Paid and in good standing
  "trialing",           // Within the 14-day free trial window
  "past_due",           // Payment failed; grace period active
  "canceled",           // Subscription terminated
  "incomplete",         // Initial payment not yet confirmed
  "incomplete_expired", // Initial payment window expired
  "unpaid",             // All retry attempts exhausted
]);

/** Individual payment transaction states — written on every webhook event */
export const paymentStatusEnum = pgEnum("payment_status", [
  "pending",   // Webhook received; not yet confirmed on-chain / by provider
  "completed", // Successfully charged / confirmed
  "failed",    // Payment attempt failed
  "refunded",  // Refunded by admin or auto-refund
]);

/** Financial instrument categories tracked by the AI engine */
export const assetTypeEnum = pgEnum("asset_type", [
  "forex",     // e.g. EURUSD, GBPJPY
  "crypto",    // e.g. BTC, ETH
  "stock",     // e.g. AAPL, TSLA
  "commodity", // e.g. Gold (XAUUSD), Oil (WTI)
  "index",     // e.g. S&P 500, Nasdaq
]);

/**
 * Post type differentiates the two content streams in the feed:
 * - ai_insight: F1 — generated by the multi-model engine (Claude → GPT-4o → Gemini → Perplexity)
 * - ict_bias:   F2 — expert-authored ICT Daily Bias Report, published via admin TipTap editor
 */
export const postTypeEnum = pgEnum("post_type", ["ai_insight", "ict_bias"]);

/** Publication state — drafts are invisible to users */
export const postStatusEnum = pgEnum("post_status", ["draft", "published"]);

/**
 * Market directional bias — the primary AI output for every insight.
 * Also used in the CB Speech Decoder (F6) for hawkish/dovish classification.
 */
export const directionEnum = pgEnum("direction", [
  "bullish",  // Long bias; upward price expectation
  "bearish",  // Short bias; downward price expectation
  "neutral",  // No clear directional edge
]);

/**
 * Bias type — a more granular tone classification.
 * Standard values mirror directionEnum for most assets.
 * Hawkish/Dovish added for CB Speech Decoder (F6) sentence-level decoding.
 */
export const biasTypeEnum = pgEnum("bias_type", [
  "bullish",
  "bearish",
  "neutral",
  "hawkish", // F6: Central bank language implying rate hikes / tightening
  "dovish",  // F6: Central bank language implying rate cuts / easing
]);

// ═══════════════════════════════════════════════════════════════════════════════
// §2 — AUTH.JS v5 TABLES  (@auth/drizzle-adapter compatible)
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * users — Core identity table, extended for Trade Insight Daily's 3-tier gating.
 *
 * Auth.js REQUIRES id to be `text`. This is the source of truth for all FK type
 * decisions. Any table referencing a user MUST use text("user_id"), never integer.
 *
 * Tier derivation in getUserTier() reads:
 *   1. isPro = true                         → Premium
 *   2. trialEndsAt IS NOT NULL AND > now()  → Premium (trial)
 *   3. Otherwise                            → Free (ad-supported)
 *   4. No session                           → Guest
 */
export const users = pgTable("users", {
  // ── Required by @auth/drizzle-adapter ──
  id: text("id")
    .notNull()
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID()),
  name: text("name"),
  email: text("email").notNull().unique(),
  emailVerified: timestamp("email_verified", { mode: "date" }),
  image: text("image"),

  // ── 3-Tier gating fields ──
  role: userRoleEnum("role").notNull().default("user"),

  /** Set to true by Stripe/PayPal/Crypto/bKash webhook on active subscription */
  isPro: boolean("is_pro").notNull().default(false),

  /**
   * Set to NOW() + 14 days at registration (both email and Google OAuth).
   * Auto-activated — no opt-in required. Non-reinstatable once expired.
   * getUserTier() treats trialEndsAt > now() as equivalent to isPro = true.
   */
  trialEndsAt: timestamp("trial_ends_at", { mode: "date" }),

  // ── Credentials auth (email/password flow) ──
  /** bcrypt hash, cost factor 12. NULL for OAuth-only users. */
  passwordHash: text("password_hash"),

  // ── Payment integration cache ──
  /** Cached to avoid repeated Stripe API lookups on checkout / portal creation */
  stripeCustomerId: text("stripe_customer_id").unique(),

  // ── Audit ──
  createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
});

/**
 * accounts — OAuth provider token storage.
 * Standard @auth/drizzle-adapter table. Do not rename columns.
 */
export const accounts = pgTable(
  "accounts",
  {
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    type: text("type").$type<AdapterAccount["type"]>().notNull(),
    provider: text("provider").notNull(),
    providerAccountId: text("provider_account_id").notNull(),
    refresh_token: text("refresh_token"),
    access_token: text("access_token"),
    expires_at: integer("expires_at"),
    token_type: text("token_type"),
    scope: text("scope"),
    id_token: text("id_token"),
    session_state: text("session_state"),
  },
  (account) => ({
    compoundKey: primaryKey({
      columns: [account.provider, account.providerAccountId],
    }),
    userIdIdx: index("accounts_user_id_idx").on(account.userId),
  })
);

/**
 * sessions — Database session store for Auth.js.
 * Standard @auth/drizzle-adapter table. Do not rename columns.
 */
export const sessions = pgTable(
  "sessions",
  {
    sessionToken: text("session_token").notNull().primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    expires: timestamp("expires", { mode: "date" }).notNull(),
  },
  (session) => ({
    userIdIdx: index("sessions_user_id_idx").on(session.userId),
  })
);

/**
 * verificationTokens — Email magic link / OTP tokens.
 * Standard @auth/drizzle-adapter table. Do not rename columns.
 */
export const verificationTokens = pgTable(
  "verification_tokens",
  {
    identifier: text("identifier").notNull(),
    token: text("token").notNull(),
    expires: timestamp("expires", { mode: "date" }).notNull(),
  },
  (vt) => ({
    compoundKey: primaryKey({ columns: [vt.identifier, vt.token] }),
  })
);

// ═══════════════════════════════════════════════════════════════════════════════
// §3 — PAYMENT TABLES
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * subscriptions — One active row per user per gateway subscription.
 *
 * Multi-gateway design rationale:
 * ┌──────────┬─────────────────────────────────────────────────────────────────┐
 * │ Gateway  │ providerSubscriptionId format                                   │
 * ├──────────┼─────────────────────────────────────────────────────────────────┤
 * │ Stripe   │ "sub_1NxABC..."  (Stripe Subscription ID)                       │
 * │ PayPal   │ "I-BW452GLLEP1G" (PayPal Subscription ID)                       │
 * │ Crypto   │ On-chain tx hash or payment processor's order ID               │
 * │ bKash    │ bKash Transaction ID (e.g. "8CK1ABC2D3")                        │
 * └──────────┴─────────────────────────────────────────────────────────────────┘
 *
 * planType vocabulary:
 *   "monthly"  — Stripe monthly recurring / equivalent in other gateways
 *   "annual"   — Stripe annual recurring / equivalent in other gateways
 *   "one_time" — Non-recurring (Crypto, bKash one-off payments)
 *
 * Webhook handlers update `status` and `currentPeriodEnd` to drive isPro logic:
 *   - Stripe:  checkout.session.completed → active; customer.subscription.deleted → canceled
 *   - PayPal:  BILLING.SUBSCRIPTION.ACTIVATED → active; BILLING.SUBSCRIPTION.CANCELLED → canceled
 *   - Crypto:  on-chain confirmation callback → active; expiry check by cron
 *   - bKash:   payment_success callback → active; manual management
 *
 * FK type: userId = text (matches users.id — text). Bug #11 prevention.
 */
export const subscriptions = pgTable(
  "subscriptions",
  {
    id: serial("id").primaryKey(),

    // TEXT — must match users.id (text). Bug #11 prevention.
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),

    provider: paymentProviderEnum("provider").notNull(),

    /** Gateway's own identifier for this subscription or order */
    providerSubscriptionId: text("provider_subscription_id").notNull(),

    status: subscriptionStatusEnum("status").notNull().default("active"),

    /** Plan duration: 'monthly' | 'annual' | 'one_time' */
    planType: text("plan_type").notNull().default("monthly"),

    currentPeriodStart: timestamp("current_period_start", { mode: "date" }),

    /**
     * getUserTier() checks: isPro = true AND currentPeriodEnd > now()
     * Updated on every billing cycle webhook event.
     */
    currentPeriodEnd: timestamp("current_period_end", { mode: "date" }),

    /** Stripe: set when user clicks "Cancel at period end" in Customer Portal */
    cancelAtPeriodEnd: boolean("cancel_at_period_end").notNull().default(false),

    canceledAt: timestamp("canceled_at", { mode: "date" }),

    /** Gateway-level trial end (separate from our 14-day platform trial) */
    trialEnd: timestamp("trial_end", { mode: "date" }),

    // ── Audit ──
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (sub) => ({
    userIdIdx: index("subscriptions_user_id_idx").on(sub.userId),
    statusIdx: index("subscriptions_status_idx").on(sub.status),
    /**
     * Unique constraint on (provider, providerSubscriptionId) ensures idempotent
     * webhook processing — duplicate events from any gateway are safely ignored.
     */
    uniqueProviderSubIdx: uniqueIndex("subscriptions_provider_sub_id_idx").on(
      sub.provider,
      sub.providerSubscriptionId
    ),
  })
);

/**
 * payments — Immutable transaction log across all gateways.
 *
 * Every payment event writes a new row here regardless of gateway:
 *   Stripe   → invoice.payment_succeeded fires on every billing cycle renewal
 *   PayPal   → PAYMENT.CAPTURE.COMPLETED fires on order capture
 *   Crypto   → on-chain confirmation callback fires once per tx
 *   bKash    → payment_success callback fires once per transaction
 *
 * `transactionId` must be globally unique — used as an idempotency key in
 * all webhook handlers to prevent double-processing on gateway retries.
 *
 * `amount` is stored as a decimal string in the major currency unit (e.g. "9.99"
 * for $9.99 USD). Do NOT store in smallest unit (cents) here — use the provider's
 * native representation after normalisation in the webhook handler.
 *
 * `metadata` holds the raw JSON webhook payload as a string for full audit trail
 * and future dispute resolution.
 *
 * FK types:
 *   userId         = text    (matches users.id — text)
 *   subscriptionId = integer (matches subscriptions.id — serial)
 */
export const payments = pgTable(
  "payments",
  {
    id: serial("id").primaryKey(),

    // TEXT — must match users.id (text). Bug #11 prevention.
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),

    // INTEGER — must match subscriptions.id (serial). Bug #11 prevention.
    subscriptionId: integer("subscription_id").references(
      () => subscriptions.id,
      { onDelete: "set null" } // keep payment record even if subscription is deleted
    ),

    provider: paymentProviderEnum("provider").notNull(),

    /**
     * Gateway-specific transaction identifier used for idempotency:
     *   Stripe:  charge_id or invoice_id  (e.g. "ch_3NxABC...")
     *   PayPal:  capture_id               (e.g. "5O190127TN364715T")
     *   Crypto:  on-chain tx hash         (e.g. "0x1abc...")
     *   bKash:   trxID                    (e.g. "8CK1ABC2D3")
     */
    transactionId: text("transaction_id").notNull(),

    /** Major currency unit (e.g. 9.99 for $9.99). Precision: 10,2 */
    amount: decimal("amount", { precision: 10, scale: 2 }).notNull(),

    /** ISO 4217 currency code (e.g. "USD", "BDT", "EUR") */
    currency: text("currency").notNull().default("USD"),

    status: paymentStatusEnum("status").notNull().default("pending"),

    /** Raw webhook payload JSON — stored for audit trail and dispute resolution */
    metadata: text("metadata"),

    // ── Audit ──
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
  },
  (payment) => ({
    userIdIdx: index("payments_user_id_idx").on(payment.userId),
    subscriptionIdIdx: index("payments_subscription_id_idx").on(
      payment.subscriptionId
    ),
    /**
     * Unique constraint on transactionId is the idempotency guard.
     * Webhook handlers should upsert on this key to safely handle retries.
     */
    transactionIdIdx: uniqueIndex("payments_transaction_id_idx").on(
      payment.transactionId
    ),
    providerIdx: index("payments_provider_idx").on(payment.provider),
    statusIdx: index("payments_status_idx").on(payment.status),
  })
);

// ═══════════════════════════════════════════════════════════════════════════════
// §4 — CONTENT TABLES
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * assets — Financial instruments tracked across the platform.
 *
 * Seeded by src/db/seed.ts with the initial 20+ Forex and Crypto assets.
 * Managed via the admin panel: /admin/assets
 *
 * id is serial (integer). All assetId FK references MUST be integer.
 * Bug #11 prevention: never use text() for assetId in any FK column.
 */
export const assets = pgTable(
  "assets",
  {
    id: serial("id").primaryKey(), // INTEGER — assetId FKs must be integer

    /** Full display name (e.g. "Euro / US Dollar", "Bitcoin") */
    name: text("name").notNull(),

    /** Trading symbol used by AI engine and feed display (e.g. "EURUSD", "BTCUSD") */
    ticker: text("ticker").notNull().unique(),

    type: assetTypeEnum("type").notNull(),

    /** Optional short description shown in asset detail views */
    description: text("description"),

    /** Soft-delete flag — inactive assets are excluded from engine runs */
    isActive: boolean("is_active").notNull().default(true),

    // ── Audit ──
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (asset) => ({
    tickerIdx: uniqueIndex("assets_ticker_idx").on(asset.ticker),
    typeIdx: index("assets_type_idx").on(asset.type),
    isActiveIdx: index("assets_is_active_idx").on(asset.isActive),
  })
);

/**
 * posts — Unified content table for all insight types.
 *
 * ┌─────────────────────────────────────────────────────────────────────────────┐
 * │ F1 — AI Insight (type = 'ai_insight')                                       │
 * │   Author: engine.actions.ts (userId = admin system account)                 │
 * │   direction, biasType, confidence: computed by AI multi-model chain         │
 * │   isProOnly: false — free users see with 24h delay                          │
 * │   Published automatically by the Vercel cron job at 06:00 UTC               │
 * ├─────────────────────────────────────────────────────────────────────────────┤
 * │ F2 — ICT Daily Bias Report (type = 'ict_bias')                              │
 * │   Author: admin user via TipTap editor in /admin/posts                      │
 * │   direction, biasType, confidence: set manually by admin before publish     │
 * │   isProOnly: true — Premium gets instant access; Free unlocks after 24h     │
 * │   Published manually by admin; publishedAt is set on explicit publish action│
 * └─────────────────────────────────────────────────────────────────────────────┘
 *
 * The 24-hour ICT unlock logic in the feed reads:
 *   isPro = true OR now() > publishedAt + INTERVAL '24 hours'
 *
 * FK types:
 *   userId  = text    (matches users.id — text)    Bug #11 prevention
 *   assetId = integer (matches assets.id — serial)  Bug #11 prevention
 */
export const posts = pgTable(
  "posts",
  {
    id: serial("id").primaryKey(),

    // TEXT — must match users.id (text). Bug #11 prevention.
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),

    // INTEGER — must match assets.id (serial). Bug #11 prevention.
    assetId: integer("asset_id")
      .notNull()
      .references(() => assets.id, { onDelete: "restrict" }),

    type: postTypeEnum("type").notNull().default("ai_insight"),
    status: postStatusEnum("status").notNull().default("draft"),

    // ── Standard content fields ──
    /** Display title (e.g. "EURUSD — Bearish Continuation Setup | April 15") */
    title: text("title").notNull(),

    /**
     * HTML body from TipTap editor (ICT posts) or AI-generated HTML (AI insights).
     * Rendered directly in the feed card and insight detail view.
     */
    body: text("body").notNull(),

    // ── AI-generated / admin-set meta fields ──
    /**
     * Primary directional call — the most prominent data point on the feed card.
     * AI-computed for ai_insight; admin-selected for ict_bias.
     */
    direction: directionEnum("direction"),

    /**
     * Granular tone / bias type.
     * For most posts mirrors `direction`. Supports hawkish/dovish for F6 posts.
     */
    biasType: biasTypeEnum("bias_type"),

    /**
     * AI confidence score: 0–100.
     * Displayed as a progress bar on the feed card.
     * For ICT posts: admin-entered qualitative confidence (50 / 75 / 100).
     */
    confidence: integer("confidence"),

    /**
     * Gates the 24-hour unlock behaviour for ICT posts.
     * true  → Premium-only until publishedAt + 24h, then unlocked for Free
     * false → Available to Free immediately (AI insights)
     */
    isProOnly: boolean("is_pro_only").notNull().default(false),

    /**
     * Populated when admin clicks "Publish" or when the engine cron publishes.
     * NULL while status = 'draft'. Used for 24h ICT unlock arithmetic.
     */
    publishedAt: timestamp("published_at", { mode: "date" }),

    // ── Audit ──
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (post) => ({
    userIdIdx: index("posts_user_id_idx").on(post.userId),
    assetIdIdx: index("posts_asset_id_idx").on(post.assetId),
    statusIdx: index("posts_status_idx").on(post.status),
    typeIdx: index("posts_type_idx").on(post.type),
    /** Indexed for feed ordering and 24h unlock arithmetic */
    publishedAtIdx: index("posts_published_at_idx").on(post.publishedAt),
    /** Composite index for the primary feed query: status + type + publishedAt */
    feedQueryIdx: index("posts_feed_query_idx").on(
      post.status,
      post.type,
      post.publishedAt
    ),
  })
);

/**
 * savedPosts — User bookmarking / reading list feature.
 *
 * Used in the /saved route and powered by save-insight.ts server action
 * with optimistic UI updates (React 19 useOptimistic).
 *
 * Composite unique key on (userId, postId) prevents duplicate bookmarks and
 * enables safe upsert patterns in the save/unsave toggle action.
 *
 * FK types:
 *   userId = text    (matches users.id — text)    Bug #11 prevention
 *   postId = integer (matches posts.id — serial)   Bug #11 prevention
 */
export const savedPosts = pgTable(
  "saved_posts",
  {
    id: serial("id").primaryKey(),

    // TEXT — must match users.id (text). Bug #11 prevention.
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),

    // INTEGER — must match posts.id (serial). Bug #11 prevention.
    postId: integer("post_id")
      .notNull()
      .references(() => posts.id, { onDelete: "cascade" }),

    savedAt: timestamp("saved_at", { mode: "date" }).notNull().defaultNow(),
  },
  (saved) => ({
    /**
     * Composite unique index prevents duplicate bookmarks and serves as the
     * lookup key for the toggle action: "is this post saved by this user?"
     */
    uniqueUserPostIdx: uniqueIndex("saved_posts_user_post_idx").on(
      saved.userId,
      saved.postId
    ),
    userIdIdx: index("saved_posts_user_id_idx").on(saved.userId),
    postIdIdx: index("saved_posts_post_id_idx").on(saved.postId),
  })
);

// ═══════════════════════════════════════════════════════════════════════════════
// §5 — DRIZZLE RELATIONS
// Defines the relational graph used by Drizzle's `with` query builder.
// These do not create DB constraints — foreign keys above do that.
// ═══════════════════════════════════════════════════════════════════════════════

export const usersRelations = relations(users, ({ many }) => ({
  /** All OAuth provider accounts linked to this user */
  accounts: many(accounts),
  /** Active database sessions */
  sessions: many(sessions),
  /** Posts authored by this user (admin creates these) */
  posts: many(posts),
  /** All subscription records across all gateways */
  subscriptions: many(subscriptions),
  /** Complete payment transaction history across all gateways */
  payments: many(payments),
  /** Bookmarked posts */
  savedPosts: many(savedPosts),
}));

export const accountsRelations = relations(accounts, ({ one }) => ({
  user: one(users, {
    fields: [accounts.userId],
    references: [users.id],
  }),
}));

export const sessionsRelations = relations(sessions, ({ one }) => ({
  user: one(users, {
    fields: [sessions.userId],
    references: [users.id],
  }),
}));

export const subscriptionsRelations = relations(
  subscriptions,
  ({ one, many }) => ({
    user: one(users, {
      fields: [subscriptions.userId],
      references: [users.id],
    }),
    /** All payment events linked to this subscription */
    payments: many(payments),
  })
);

export const paymentsRelations = relations(payments, ({ one }) => ({
  user: one(users, {
    fields: [payments.userId],
    references: [users.id],
  }),
  subscription: one(subscriptions, {
    fields: [payments.subscriptionId],
    references: [subscriptions.id],
  }),
}));

export const assetsRelations = relations(assets, ({ many }) => ({
  /** All posts (both AI insights and ICT bias reports) for this asset */
  posts: many(posts),
}));

export const postsRelations = relations(posts, ({ one, many }) => ({
  /** The admin user who authored or triggered this post */
  author: one(users, {
    fields: [posts.userId],
    references: [users.id],
  }),
  /** The financial instrument this post analyses */
  asset: one(assets, {
    fields: [posts.assetId],
    references: [assets.id],
  }),
  /** All users who have bookmarked this post */
  savedBy: many(savedPosts),
}));

export const savedPostsRelations = relations(savedPosts, ({ one }) => ({
  user: one(users, {
    fields: [savedPosts.userId],
    references: [users.id],
  }),
  post: one(posts, {
    fields: [savedPosts.postId],
    references: [posts.id],
  }),
}));

// ═══════════════════════════════════════════════════════════════════════════════
// §6 — TYPE EXPORTS
// Inferred TypeScript types for use in Server Actions and RSC props.
// Import these instead of manually declaring types to stay in sync with schema.
// ═══════════════════════════════════════════════════════════════════════════════

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;

export type Account = typeof accounts.$inferSelect;
export type NewAccount = typeof accounts.$inferInsert;

export type Session = typeof sessions.$inferSelect;

export type Subscription = typeof subscriptions.$inferSelect;
export type NewSubscription = typeof subscriptions.$inferInsert;

export type Payment = typeof payments.$inferSelect;
export type NewPayment = typeof payments.$inferInsert;

export type Asset = typeof assets.$inferSelect;
export type NewAsset = typeof assets.$inferInsert;

export type Post = typeof posts.$inferSelect;
export type NewPost = typeof posts.$inferInsert;

export type SavedPost = typeof savedPosts.$inferSelect;
export type NewSavedPost = typeof savedPosts.$inferInsert;

// ── Convenience union types for use in gating logic ──
export type UserRole = (typeof userRoleEnum.enumValues)[number];
export type PaymentProvider = (typeof paymentProviderEnum.enumValues)[number];
export type SubscriptionStatus =
  (typeof subscriptionStatusEnum.enumValues)[number];
export type PaymentStatus = (typeof paymentStatusEnum.enumValues)[number];
export type AssetType = (typeof assetTypeEnum.enumValues)[number];
export type PostType = (typeof postTypeEnum.enumValues)[number];
export type PostStatus = (typeof postStatusEnum.enumValues)[number];
export type Direction = (typeof directionEnum.enumValues)[number];
export type BiasType = (typeof biasTypeEnum.enumValues)[number];