// src/db/schema.ts
// Trade Insight Daily — Complete Drizzle ORM Schema
// Compatible with: Auth.js v5 (@auth/drizzle-adapter), Next.js 15, PostgreSQL (Neon)
//
// FK TYPE CONTRACT (Bug #11 Prevention):
//   users.id        → text  ∴ userId  in posts / subscriptions / payments / savedPosts = text
//   assets.id       → serial (int) ∴ assetId in posts = integer
//   subscriptions.id → serial (int) ∴ subscriptionId in payments = integer
//   posts.id        → serial (int) ∴ postId in savedPosts = integer

import {
  pgTable,
  pgEnum,
  text,
  boolean,
  timestamp,
  integer,
  serial,
  decimal,
  primaryKey,
  index,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";
import type { AdapterAccount } from "@auth/core/adapters";

// ═══════════════════════════════════════════════════════════════════════════════
// §1 — ENUMS
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Platform role — used to gate admin panel DB queries.
 * Note: Admin panel *login* uses a separate HMAC cookie system (not this role).
 * This role is for identifying admin users at the data layer.
 */
export const userRoleEnum = pgEnum("user_role", ["user", "admin"]);

/**
 * Multi-gateway payment providers.
 * Each provider has its own webhook handler under /api/webhooks/{provider}/route.ts
 * and its own server action under /actions/payments/{provider}.actions.ts
 */
export const paymentProviderEnum = pgEnum("payment_provider", [
  "stripe",  // Primary: Cards, Apple Pay, Google Pay — global
  "paypal",  // Alternative: PayPal Wallet — NA, EU, SEA
  "crypto",  // Web3: On-chain payments — DeFi community
  "bkash",   // Local: Mobile Money — Bangladesh / South Asia (60M+ users)
]);

/**
 * Subscription lifecycle states.
 * Mirrors Stripe's status vocabulary — other gateways are mapped to these same states
 * in their respective webhook handlers for a unified status model.
 */
export const subscriptionStatusEnum = pgEnum("subscription_status", [
  "active",             // Paid and in good standing
  "trialing",           // Within the 14-day free trial window
  "past_due",           // Payment failed; grace period active
  "canceled",           // Subscription terminated
  "incomplete",         // Initial payment not yet confirmed
  "incomplete_expired", // Initial payment window expired
  "unpaid",             // All retry attempts exhausted
]);

/** Individual payment transaction states — written on every webhook event */
export const paymentStatusEnum = pgEnum("payment_status", [
  "pending",   // Webhook received; not yet confirmed on-chain / by provider
  "completed", // Successfully charged / confirmed
  "failed",    // Payment attempt failed
  "refunded",  // Refunded by admin or auto-refund
]);

/** Financial instrument categories tracked by the AI engine */
export const assetTypeEnum = pgEnum("asset_type", [
  "forex",     // e.g. EURUSD, GBPJPY
  "crypto",    // e.g. BTC, ETH
  "stock",     // e.g. AAPL, TSLA
  "commodity", // e.g. Gold (XAUUSD), Oil (WTI)
  "index",     // e.g. S&P 500, Nasdaq
]);

/**
 * Post type differentiates the two content streams in the feed:
 * - ai_insight: F1 — generated by the multi-model engine (Claude → GPT-4o → Gemini → Perplexity)
 * - ict_bias:   F2 — expert-authored ICT Daily Bias Report, published via admin TipTap editor
 */
export const postTypeEnum = pgEnum("post_type", ["ai_insight", "ict_bias"]);

/** Publication state — drafts are invisible to users */
export const postStatusEnum = pgEnum("post_status", ["draft", "published"]);

/**
 * Market directional bias — the primary AI output for every insight.
 * Also used in the CB Speech Decoder (F6) for hawkish/dovish classification.
 */
export const directionEnum = pgEnum("direction", [
  "bullish",  // Long bias; upward price expectation
  "bearish",  // Short bias; downward price expectation
  "neutral",  // No clear directional edge
]);

/**
 * Bias type — a more granular tone classification.
 * Standard values mirror directionEnum for most assets.
 * Hawkish/Dovish added for CB Speech Decoder (F6) sentence-level decoding.
 */
export const biasTypeEnum = pgEnum("bias_type", [
  "bullish",
  "bearish",
  "neutral",
  "hawkish", // F6: Central bank language implying rate hikes / tightening
  "dovish",  // F6: Central bank language implying rate cuts / easing
]);

// ═══════════════════════════════════════════════════════════════════════════════
// §2 — AUTH.JS v5 TABLES  (@auth/drizzle-adapter compatible)
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * users — Core identity table, extended for Trade Insight Daily's 3-tier gating.
 *
 * Auth.js REQUIRES id to be `text`. This is the source of truth for all FK type
 * decisions. Any table referencing a user MUST use text("user_id"), never integer.
 *
 * Tier derivation in getUserTier() reads:
 *   1. isPro = true                         → Premium
 *   2. trialEndsAt IS NOT NULL AND > now()  → Premium (trial)
 *   3. Otherwise                            → Free (ad-supported)
 *   4. No session                           → Guest
 */
export const users = pgTable("users", {
  // ── Required by @auth/drizzle-adapter ──
  id: text("id")
    .notNull()
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID()),
  name: text("name"),
  email: text("email").notNull().unique(),
  emailVerified: timestamp("email_verified", { mode: "date" }),
  image: text("image"),

  // ── 3-Tier gating fields ──
  role: userRoleEnum("role").notNull().default("user"),

  /** Set to true by Stripe/PayPal/Crypto/bKash webhook on active subscription */
  isPro: boolean("is_pro").notNull().default(false),

  /**
   * Set to NOW() + 14 days at registration (both email and Google OAuth).
   * Auto-activated — no opt-in required. Non-reinstatable once expired.
   * getUserTier() treats trialEndsAt > now() as equivalent to isPro = true.
   */
  trialEndsAt: timestamp("trial_ends_at", { mode: "date" }),

  // ── Credentials auth (email/password flow) ──
  /** bcrypt hash, cost factor 12. NULL for OAuth-only users. */
  passwordHash: text("password_hash"),

  // ── Payment integration cache ──
  /** Cached to avoid repeated Stripe API lookups on checkout / portal creation */
  stripeCustomerId: text("stripe_customer_id").unique(),

  // ── Audit ──
  createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
});

/**
 * accounts — OAuth provider token storage.
 * Standard @auth/drizzle-adapter table. Do not rename columns.
 */
export const accounts = pgTable(
  "accounts",
  {
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    type: text("type").$type<AdapterAccount["type"]>().notNull(),
    provider: text("provider").notNull(),
    providerAccountId: text("provider_account_id").notNull(),
    refresh_token: text("refresh_token"),
    access_token: text("access_token"),
    expires_at: integer("expires_at"),
    token_type: text("token_type"),
    scope: text("scope"),
    id_token: text("id_token"),
    session_state: text("session_state"),
  },
  (account) => ({
    compoundKey: primaryKey({
      columns: [account.provider, account.providerAccountId],
    }),
    userIdIdx: index("accounts_user_id_idx").on(account.userId),
  })
);

/**
 * sessions — Database session store for Auth.js.
 * Standard @auth/drizzle-adapter table. Do not rename columns.
 */
export const sessions = pgTable(
  "sessions",
  {
    sessionToken: text("session_token").notNull().primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    expires: timestamp("expires", { mode: "date" }).notNull(),
  },
  (session) => ({
    userIdIdx: index("sessions_user_id_idx").on(session.userId),
  })
);

/**
 * verificationTokens — Email magic link / OTP tokens.
 * Standard @auth/drizzle-adapter table. Do not rename columns.
 */
export const verificationTokens = pgTable(
  "verification_tokens",
  {
    identifier: text("identifier").notNull(),
    token: text("token").notNull(),
    expires: timestamp("expires", { mode: "date" }).notNull(),
  },
  (vt) => ({
    compoundKey: primaryKey({ columns: [vt.identifier, vt.token] }),
  })
);

// ═══════════════════════════════════════════════════════════════════════════════
// §3 — PAYMENT TABLES
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * subscriptions — One active row per user per gateway subscription.
 *
 * Multi-gateway design rationale:
 * ┌──────────┬─────────────────────────────────────────────────────────────────┐
 * │ Gateway  │ providerSubscriptionId format                                   │
 * ├──────────┼─────────────────────────────────────────────────────────────────┤
 * │ Stripe   │ "sub_1NxABC..."  (Stripe Subscription ID)                       │
 * │ PayPal   │ "I-BW452GLLEP1G" (PayPal Subscription ID)                       │
 * │ Crypto   │ On-chain tx hash or payment processor's order ID               │
 * │ bKash    │ bKash Transaction ID (e.g. "8CK1ABC2D3")                        │
 * └──────────┴─────────────────────────────────────────────────────────────────┘
 *
 * planType vocabulary:
 *   "monthly"  — Stripe monthly recurring / equivalent in other gateways
 *   "annual"   — Stripe annual recurring / equivalent in other gateways
 *   "one_time" — Non-recurring (Crypto, bKash one-off payments)
 *
 * Webhook handlers update `status` and `currentPeriodEnd` to drive isPro logic:
 *   - Stripe:  checkout.session.completed → active; customer.subscription.deleted → canceled
 *   - PayPal:  BILLING.SUBSCRIPTION.ACTIVATED → active; BILLING.SUBSCRIPTION.CANCELLED → canceled
 *   - Crypto:  on-chain confirmation callback → active; expiry check by cron
 *   - bKash:   payment_success callback → active; manual management
 *
 * FK type: userId = text (matches users.id — text). Bug #11 prevention.
 */
export const subscriptions = pgTable(
  "subscriptions",
  {
    id: serial("id").primaryKey(),

    // TEXT — must match users.id (text). Bug #11 prevention.
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),

    provider: paymentProviderEnum("provider").notNull(),

    /** Gateway's own identifier for this subscription or order */
    providerSubscriptionId: text("provider_subscription_id").notNull(),

    status: subscriptionStatusEnum("status").notNull().default("active"),

    /** Plan duration: 'monthly' | 'annual' | 'one_time' */
    planType: text("plan_type").notNull().default("monthly"),

    currentPeriodStart: timestamp("current_period_start", { mode: "date" }),

    /**
     * getUserTier() checks: isPro = true AND currentPeriodEnd > now()
     * Updated on every billing cycle webhook event.
     */
    currentPeriodEnd: timestamp("current_period_end", { mode: "date" }),

    /** Stripe: set when user clicks "Cancel at period end" in Customer Portal */
    cancelAtPeriodEnd: boolean("cancel_at_period_end").notNull().default(false),

    canceledAt: timestamp("canceled_at", { mode: "date" }),

    /** Gateway-level trial end (separate from our 14-day platform trial) */
    trialEnd: timestamp("trial_end", { mode: "date" }),

    // ── Audit ──
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (sub) => ({
    userIdIdx: index("subscriptions_user_id_idx").on(sub.userId),
    statusIdx: index("subscriptions_status_idx").on(sub.status),
    /**
     * Unique constraint on (provider, providerSubscriptionId) ensures idempotent
     * webhook processing — duplicate events from any gateway are safely ignored.
     */
    uniqueProviderSubIdx: uniqueIndex("subscriptions_provider_sub_id_idx").on(
      sub.provider,
      sub.providerSubscriptionId
    ),
  })
);

/**
 * payments — Immutable transaction log across all gateways.
 *
 * Every payment event writes a new row here regardless of gateway:
 *   Stripe   → invoice.payment_succeeded fires on every billing cycle renewal
 *   PayPal   → PAYMENT.CAPTURE.COMPLETED fires on order capture
 *   Crypto   → on-chain confirmation callback fires once per tx
 *   bKash    → payment_success callback fires once per transaction
 *
 * `transactionId` must be globally unique — used as an idempotency key in
 * all webhook handlers to prevent double-processing on gateway retries.
 *
 * `amount` is stored as a decimal string in the major currency unit (e.g. "9.99"
 * for $9.99 USD). Do NOT store in smallest unit (cents) here — use the provider's
 * native representation after normalisation in the webhook handler.
 *
 * `metadata` holds the raw JSON webhook payload as a string for full audit trail
 * and future dispute resolution.
 *
 * FK types:
 *   userId         = text    (matches users.id — text)
 *   subscriptionId = integer (matches subscriptions.id — serial)
 */
export const payments = pgTable(
  "payments",
  {
    id: serial("id").primaryKey(),

    // TEXT — must match users.id (text). Bug #11 prevention.
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),

    // INTEGER — must match subscriptions.id (serial). Bug #11 prevention.
    subscriptionId: integer("subscription_id").references(
      () => subscriptions.id,
      { onDelete: "set null" } // keep payment record even if subscription is deleted
    ),

    provider: paymentProviderEnum("provider").notNull(),

    /**
     * Gateway-specific transaction identifier used for idempotency:
     *   Stripe:  charge_id or invoice_id  (e.g. "ch_3NxABC...")
     *   PayPal:  capture_id               (e.g. "5O190127TN364715T")
     *   Crypto:  on-chain tx hash         (e.g. "0x1abc...")
     *   bKash:   trxID                    (e.g. "8CK1ABC2D3")
     */
    transactionId: text("transaction_id").notNull(),

    /** Major currency unit (e.g. 9.99 for $9.99). Precision: 10,2 */
    amount: decimal("amount", { precision: 10, scale: 2 }).notNull(),

    /** ISO 4217 currency code (e.g. "USD", "BDT", "EUR") */
    currency: text("currency").notNull().default("USD"),

    status: paymentStatusEnum("status").notNull().default("pending"),

    /** Raw webhook payload JSON — stored for audit trail and dispute resolution */
    metadata: text("metadata"),

    // ── Audit ──
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
  },
  (payment) => ({
    userIdIdx: index("payments_user_id_idx").on(payment.userId),
    subscriptionIdIdx: index("payments_subscription_id_idx").on(
      payment.subscriptionId
    ),
    /**
     * Unique constraint on transactionId is the idempotency guard.
     * Webhook handlers should upsert on this key to safely handle retries.
     */
    transactionIdIdx: uniqueIndex("payments_transaction_id_idx").on(
      payment.transactionId
    ),
    providerIdx: index("payments_provider_idx").on(payment.provider),
    statusIdx: index("payments_status_idx").on(payment.status),
  })
);

// ═══════════════════════════════════════════════════════════════════════════════
// §4 — CONTENT TABLES
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * assets — Financial instruments tracked across the platform.
 *
 * Seeded by src/db/seed.ts with the initial 20+ Forex and Crypto assets.
 * Managed via the admin panel: /admin/assets
 *
 * id is serial (integer). All assetId FK references MUST be integer.
 * Bug #11 prevention: never use text() for assetId in any FK column.
 */
export const assets = pgTable(
  "assets",
  {
    id: serial("id").primaryKey(), // INTEGER — assetId FKs must be integer

    // ── 🔗 Foreign Keys (CRITICAL) ──
    // কোন ক্যাটাগরির আন্ডারে এই অ্যাসেটটি আছে (e.g., Forex, Crypto)
    categoryId: integer("category_id")
      .notNull()
      .references(() => categories.id, { onDelete: "restrict" }),

    // ── 📝 Core Info ──
    /** Full display name (e.g. "Euro / US Dollar", "Bitcoin") */
    name: text("name").notNull(),

    /** Trading symbol used by AI engine and feed display (e.g. "EURUSD", "BTCUSD") */
    ticker: text("ticker").notNull().unique(),

    type: assetTypeEnum("type").notNull(),

    /** Denormalized category name for super-fast UI filtering without JOINs */
    categoryName: text("category_name"),

    /** Optional short description shown in asset detail views */
    description: text("description"),

    /** Soft-delete flag — inactive assets are excluded from engine runs */
    isActive: boolean("is_active").notNull().default(true),

    // ── 🕒 Audit ──
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (asset) => ({
    tickerIdx: uniqueIndex("assets_ticker_idx").on(asset.ticker),
    typeIdx: index("assets_type_idx").on(asset.type),
    categoryIdIdx: index("assets_category_id_idx").on(asset.categoryId), // ক্যাটাগরি দিয়ে দ্রুত খোঁজার জন্য
    isActiveIdx: index("assets_is_active_idx").on(asset.isActive),
  })
);

/**
 * posts — Unified content table for all insight types.
 *
 * ┌─────────────────────────────────────────────────────────────────────────────┐
 * │ F1 — AI Insight (type = 'ai_insight')                                       │
 * │   Author: engine.actions.ts (userId = admin system account)                 │
 * │   direction, biasType, confidence: computed by AI multi-model chain         │
 * │   isProOnly: false — free users see with 24h delay                          │
 * │   Published automatically by the Vercel cron job at 06:00 UTC               │
 * ├─────────────────────────────────────────────────────────────────────────────┤
 * │ F2 — ICT Daily Bias Report (type = 'ict_bias')                              │
 * │   Author: admin user via TipTap editor in /admin/posts                      │
 * │   direction, biasType, confidence: set manually by admin before publish     │
 * │   isProOnly: true — Premium gets instant access; Free unlocks after 24h     │
 * │   Published manually by admin; publishedAt is set on explicit publish action│
 * └─────────────────────────────────────────────────────────────────────────────┘
 *
 * The 24-hour ICT unlock logic in the feed reads:
 *   isPro = true OR now() > publishedAt + INTERVAL '24 hours'
 *
 * FK types:
 *   userId  = text    (matches users.id — text)    Bug #11 prevention
 *   assetId = integer (matches assets.id — serial)  Bug #11 prevention
 */
export const posts = pgTable(
  "posts",
  {
    id: serial("id").primaryKey(),

    // TEXT — must match users.id (text). Bug #11 prevention.
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "restrict" }),

    // INTEGER — must match assets.id (serial). Bug #11 prevention.
    // Note: Made nullable because some general market updates might not belong to a specific asset.
    assetId: integer("asset_id")
      .references(() => assets.id, { onDelete: "set null" }),

    // ── ⚡ Denormalization (Faster Feed Rendering) ──
    assetName: text("asset_name"), // e.g. "EUR/USD" (No JOIN needed)
    categoryName: text("category_name"), // e.g. "Forex" (No JOIN needed)

    type: postTypeEnum("type").notNull().default("ai_insight"),
    status: postStatusEnum("status").notNull().default("draft"),

    // ── 📝 Standard content fields ──
    /** Display title (e.g. "EURUSD — Bearish Continuation Setup | April 15") */
    title: text("title").notNull(),

    /** 🚀 NEW: SEO friendly URL identifier (e.g., "eurusd-bearish-continuation-setup") */
    slug: text("slug").notNull().unique(),

    /** 🚀 NEW: Short 2-line preview for the feed card. Saves massive bandwidth! */
    summary: text("summary"),

    /** HTML body from TipTap editor or AI. Rendered directly in the insight detail view. */
    body: text("body").notNull(),

    // ── 🤖 AI-generated / admin-set meta fields ──
    direction: directionEnum("direction"),
    biasType: biasTypeEnum("bias_type"),
    confidence: integer("confidence"),

    isProOnly: boolean("is_pro_only").notNull().default(false),

    // ── 🔍 🚀 NEW: SEO Meta Fields (For Google Ranking) ──
    metaDescription: text("meta_description"),
    metaKeywords: text("meta_keywords"),

    publishedAt: timestamp("published_at", { mode: "date" }),
    
    // ── 🕒 Audit ──
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (post) => ({
    slugIdx: uniqueIndex("posts_slug_idx").on(post.slug), // 🚀 NEW: Fast URL routing
    userIdIdx: index("posts_user_id_idx").on(post.userId),
    assetIdIdx: index("posts_asset_id_idx").on(post.assetId),
    statusIdx: index("posts_status_idx").on(post.status),
    typeIdx: index("posts_type_idx").on(post.type),
    publishedAtIdx: index("posts_published_at_idx").on(post.publishedAt),
    
    /** Composite index for the primary feed query */
    feedQueryIdx: index("posts_feed_query_idx").on(
      post.status,
      post.type,
      post.publishedAt
    ),
  })
);

/**
 * savedPosts — User bookmarking / reading list feature.
 *
 * Used in the /saved route and powered by save-insight.ts server action
 * with optimistic UI updates (React 19 useOptimistic).
 *
 * Composite unique key on (userId, postId) prevents duplicate bookmarks and
 * enables safe upsert patterns in the save/unsave toggle action.
 *
 * FK types:
 *   userId = text    (matches users.id — text)    Bug #11 prevention
 *   postId = integer (matches posts.id — serial)   Bug #11 prevention
 */
export const savedPosts = pgTable(
  "saved_posts",
  {
    id: serial("id").primaryKey(),

    // TEXT — must match users.id (text). Bug #11 prevention.
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),

    // INTEGER — must match posts.id (serial). Bug #11 prevention.
    postId: integer("post_id")
      .notNull()
      .references(() => posts.id, { onDelete: "cascade" }),

    savedAt: timestamp("saved_at", { mode: "date" }).notNull().defaultNow(),
  },
  (saved) => ({
    /**
     * Composite unique index prevents duplicate bookmarks and serves as the
     * lookup key for the toggle action: "is this post saved by this user?"
     */
    uniqueUserPostIdx: uniqueIndex("saved_posts_user_post_idx").on(
      saved.userId,
      saved.postId
    ),
    userIdIdx: index("saved_posts_user_id_idx").on(saved.userId),
    postIdIdx: index("saved_posts_post_id_idx").on(saved.postId),
  })
);

// ═══════════════════════════════════════════════════════════════════════════════
// §5 — DRIZZLE RELATIONS
// Defines the relational graph used by Drizzle's `with` query builder.
// These do not create DB constraints — foreign keys above do that.
// ═══════════════════════════════════════════════════════════════════════════════

export const usersRelations = relations(users, ({ many }) => ({
  /** All OAuth provider accounts linked to this user */
  accounts: many(accounts),
  /** Active database sessions */
  sessions: many(sessions),
  /** Posts authored by this user (admin creates these) */
  posts: many(posts),
  /** All subscription records across all gateways */
  subscriptions: many(subscriptions),
  /** Complete payment transaction history across all gateways */
  payments: many(payments),
  /** Bookmarked posts */
  savedPosts: many(savedPosts),
}));

export const accountsRelations = relations(accounts, ({ one }) => ({
  user: one(users, {
    fields: [accounts.userId],
    references: [users.id],
  }),
}));

export const sessionsRelations = relations(sessions, ({ one }) => ({
  user: one(users, {
    fields: [sessions.userId],
    references: [users.id],
  }),
}));

export const subscriptionsRelations = relations(
  subscriptions,
  ({ one, many }) => ({
    user: one(users, {
      fields: [subscriptions.userId],
      references: [users.id],
    }),
    /** All payment events linked to this subscription */
    payments: many(payments),
  })
);

export const paymentsRelations = relations(payments, ({ one }) => ({
  user: one(users, {
    fields: [payments.userId],
    references: [users.id],
  }),
  subscription: one(subscriptions, {
    fields: [payments.subscriptionId],
    references: [subscriptions.id],
  }),
}));

export const assetsRelations = relations(assets, ({ many }) => ({
  /** All posts (both AI insights and ICT bias reports) for this asset */
  posts: many(posts),
}));

export const postsRelations = relations(posts, ({ one, many }) => ({
  /** The admin user who authored or triggered this post */
  author: one(users, {
    fields: [posts.userId],
    references: [users.id],
  }),
  /** The financial instrument this post analyses */
  asset: one(assets, {
    fields: [posts.assetId],
    references: [assets.id],
  }),
  /** All users who have bookmarked this post */
  savedBy: many(savedPosts),
}));

export const savedPostsRelations = relations(savedPosts, ({ one }) => ({
  user: one(users, {
    fields: [savedPosts.userId],
    references: [users.id],
  }),
  post: one(posts, {
    fields: [savedPosts.postId],
    references: [posts.id],
  }),
}));

// ═══════════════════════════════════════════════════════════════════════════════
// §6 — TYPE EXPORTS
// Inferred TypeScript types for use in Server Actions and RSC props.
// Import these instead of manually declaring types to stay in sync with schema.
// ═══════════════════════════════════════════════════════════════════════════════

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;

export type Account = typeof accounts.$inferSelect;
export type NewAccount = typeof accounts.$inferInsert;

export type Session = typeof sessions.$inferSelect;

export type Subscription = typeof subscriptions.$inferSelect;
export type NewSubscription = typeof subscriptions.$inferInsert;

export type Payment = typeof payments.$inferSelect;
export type NewPayment = typeof payments.$inferInsert;

export type Asset = typeof assets.$inferSelect;
export type NewAsset = typeof assets.$inferInsert;

export type Post = typeof posts.$inferSelect;
export type NewPost = typeof posts.$inferInsert;

export type SavedPost = typeof savedPosts.$inferSelect;
export type NewSavedPost = typeof savedPosts.$inferInsert;

// ── Convenience union types for use in gating logic ──
export type UserRole = (typeof userRoleEnum.enumValues)[number];
export type PaymentProvider = (typeof paymentProviderEnum.enumValues)[number];
export type SubscriptionStatus =
  (typeof subscriptionStatusEnum.enumValues)[number];
export type PaymentStatus = (typeof paymentStatusEnum.enumValues)[number];
export type AssetType = (typeof assetTypeEnum.enumValues)[number];
export type PostType = (typeof postTypeEnum.enumValues)[number];
export type PostStatus = (typeof postStatusEnum.enumValues)[number];
export type Direction = (typeof directionEnum.enumValues)[number];
export type BiasType = (typeof biasTypeEnum.enumValues)[number];



// ═══════════════════════════════════════════════════════════════════════════════
// §7 — FEATURE ENUMS
// Additional enums for Phase 1 foundation tables and Phase 3–7 feature tables.
// ═══════════════════════════════════════════════════════════════════════════════

/** Shared impact vocabulary for Calendar and News features */
export const impactLevelEnum = pgEnum("impact_level", [
  "low",
  "medium",
  "high",
]);

/** GRI dashboard risk buckets */
export const riskLevelEnum = pgEnum("risk_level", [
  "low",
  "medium",
  "high",
  "extreme",
]);

/** Article sentiment used by the News pipeline */
export const newsSentimentEnum = pgEnum("news_sentiment", [
  "positive",
  "negative",
  "neutral",
]);

/** Prompt lifecycle / scope grouping */
export const promptScopeEnum = pgEnum("prompt_scope", [
  "engine",
  "calendar",
  "cot",
  "news",
  "gri",
  "correlation",
  "speech",
]);

/** Correlation interpretation bucket for UI colouring and commentary */
export const correlationStrengthEnum = pgEnum("correlation_strength", [
  "strong_negative",
  "weak_negative",
  "neutral",
  "weak_positive",
  "strong_positive",
]);

/** Supported central bank institutions for the speech decoder */
export const cbInstitutionEnum = pgEnum("cb_institution", [
  "fed",
  "ecb",
  "boe",
  "boj",
  "rba",
  "rbnz",
  "boc",
  "snb",
]);

/** Speech processing state */
export const cbSpeechStatusEnum = pgEnum("cb_speech_status", [
  "scheduled",
  "live",
  "completed",
  "canceled",
]);

/** Restricted tone vocabulary for central bank speech decoding */
export const speechToneEnum = pgEnum("speech_tone", [
  "hawkish",
  "dovish",
  "neutral",
]);

// ═══════════════════════════════════════════════════════════════════════════════
// §8 — FOUNDATION TABLES (Missing From Phase 1)
// categories + prompts
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * categories — Admin-managed grouping for reusable prompt templates.
 * Seeded once and reused across the AI engine and feature pipelines.
 */
export const categories = pgTable(
  "categories",
  {
    id: serial("id").primaryKey(),

    name: text("name").notNull(),
    slug: text("slug").notNull(),
    description: text("description"),

    /** Lower values sort first in admin listings and seed output */
    sortOrder: integer("sort_order").notNull().default(0),

    isActive: boolean("is_active").notNull().default(true),

    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (category) => ({
    slugIdx: uniqueIndex("categories_slug_idx").on(category.slug),
    sortOrderIdx: index("categories_sort_order_idx").on(category.sortOrder),
    isActiveIdx: index("categories_is_active_idx").on(category.isActive),
  })
);

/**
 * prompts — Versioned prompt templates used by the engine and feature pipelines.
 * Kept in the database so admins can evolve prompt strategy without code edits.
 */
export const prompts = pgTable(
  "prompts",
  {
    id: serial("id").primaryKey(),

    // INTEGER — must match categories.id (serial).
    categoryId: integer("category_id")
      .notNull()
      .references(() => categories.id, { onDelete: "restrict" }),

    name: text("name").notNull(),
    slug: text("slug").notNull(),
    scope: promptScopeEnum("scope").notNull().default("engine"),

    /** Optional short note describing where the prompt is used */
    description: text("description"),

    /** Split system and user templates for structured multi-model orchestration */
    systemPrompt: text("system_prompt").notNull(),
    userPrompt: text("user_prompt").notNull(),

    /** Increment when a prompt is materially revised */
    version: integer("version").notNull().default(1),

    isActive: boolean("is_active").notNull().default(true),

    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (prompt) => ({
    slugIdx: uniqueIndex("prompts_slug_idx").on(prompt.slug),
    categoryIdIdx: index("prompts_category_id_idx").on(prompt.categoryId),
    scopeIdx: index("prompts_scope_idx").on(prompt.scope),
    isActiveIdx: index("prompts_is_active_idx").on(prompt.isActive),
  })
);

// ═══════════════════════════════════════════════════════════════════════════════
// §9 — FEATURE TABLES (Phase 3–7)
// Calendar, COT, News, GRI, Correlation, Central Bank Speeches
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * economicEvents — Smart Economic Calendar source table.
 * Stores the scheduled event plus the premium AI insight payload.
 */
export const economicEvents = pgTable(
  "economic_events",
  {
    id: serial("id").primaryKey(),

    // INTEGER — must match assets.id (serial).
    assetId: integer("asset_id")
      .notNull()
      .references(() => assets.id, { onDelete: "restrict" }),

    title: text("title").notNull(),
    country: text("country").notNull(),
    currency: text("currency").notNull(),
    impactLevel: impactLevelEnum("impact_level").notNull(),

    /** Optional upstream provider identifier for de-duplication */
    sourceEventId: text("source_event_id"),

    scheduledFor: timestamp("scheduled_for", { mode: "date" }).notNull(),

    previousValue: text("previous_value"),
    forecastValue: text("forecast_value"),
    actualValue: text("actual_value"),

    /** Plain-English explanation visible to Free users */
    about: text("about"),

    /** Premium AI section for trade setup commentary */
    aiInsight: text("ai_insight"),

    isActive: boolean("is_active").notNull().default(true),

    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (event) => ({
    assetIdIdx: index("economic_events_asset_id_idx").on(event.assetId),
    scheduledForIdx: index("economic_events_scheduled_for_idx").on(
      event.scheduledFor
    ),
    impactLevelIdx: index("economic_events_impact_level_idx").on(
      event.impactLevel
    ),
    isActiveIdx: index("economic_events_is_active_idx").on(event.isActive),
    sourceEventIdIdx: uniqueIndex("economic_events_source_event_id_idx").on(
      event.sourceEventId
    ),
  })
);

/**
 * economicEventHistory — Historical release rows for a single economic event.
 * Powers the event history block in the Smart Economic Calendar detail view.
 */
export const economicEventHistory = pgTable(
  "economic_event_history",
  {
    id: serial("id").primaryKey(),

    // INTEGER — must match economicEvents.id (serial).
    eventId: integer("event_id")
      .notNull()
      .references(() => economicEvents.id, { onDelete: "cascade" }),

    releasedAt: timestamp("released_at", { mode: "date" }).notNull(),

    previousValue: text("previous_value"),
    forecastValue: text("forecast_value"),
    actualValue: text("actual_value"),
    revisionValue: text("revision_value"),

    /** Optional human-readable surprise summary */
    surpriseSummary: text("surprise_summary"),

    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
  },
  (history) => ({
    eventIdIdx: index("economic_event_history_event_id_idx").on(history.eventId),
    releasedAtIdx: index("economic_event_history_released_at_idx").on(
      history.releasedAt
    ),
    uniqueReleaseIdx: uniqueIndex("economic_event_history_event_release_idx").on(
      history.eventId,
      history.releasedAt
    ),
  })
);

/**
 * cotReports — Weekly Commitment of Traders data snapshots per asset.
 * Stores both the raw positioning numbers and the AI explanation.
 */
export const cotReports = pgTable(
  "cot_reports",
  {
    id: serial("id").primaryKey(),

    // INTEGER — must match assets.id (serial).
    assetId: integer("asset_id")
      .notNull()
      .references(() => assets.id, { onDelete: "restrict" }),

    reportDate: timestamp("report_date", { mode: "date" }).notNull(),

    nonCommercialLong: integer("non_commercial_long").notNull(),
    nonCommercialShort: integer("non_commercial_short").notNull(),
    nonCommercialNet: integer("non_commercial_net").notNull(),

    commercialLong: integer("commercial_long"),
    commercialShort: integer("commercial_short"),
    commercialNet: integer("commercial_net"),

    openInterest: integer("open_interest"),

    changeInLong: integer("change_in_long"),
    changeInShort: integer("change_in_short"),
    changeInNet: integer("change_in_net"),

    /** Free-tier explanation */
    summary: text("summary"),

    /** Premium AI insight block */
    aiInsight: text("ai_insight"),

    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (report) => ({
    assetIdIdx: index("cot_reports_asset_id_idx").on(report.assetId),
    reportDateIdx: index("cot_reports_report_date_idx").on(report.reportDate),
    uniqueAssetReportIdx: uniqueIndex("cot_reports_asset_report_date_idx").on(
      report.assetId,
      report.reportDate
    ),
  })
);

/**
 * newsArticles — News ingestion table for hourly / intraday article indexing.
 * Supports one primary asset relation plus a raw ticker list for multi-asset news.
 */
export const newsArticles = pgTable(
  "news_articles",
  {
    id: serial("id").primaryKey(),

    // INTEGER — must match assets.id (serial).
    assetId: integer("asset_id").references(() => assets.id, {
      onDelete: "set null",
    }),

    source: text("source").notNull(),
    title: text("title").notNull(),
    url: text("url").notNull(),

    summary: text("summary"),
    body: text("body"),

    impactLevel: impactLevelEnum("impact_level").notNull().default("medium"),
    sentiment: newsSentimentEnum("sentiment").notNull().default("neutral"),

    /** Comma-separated or JSON-stringified ticker list for cross-asset relevance */
    relatedTickers: text("related_tickers"),

    /** Premium AI significance explanation */
    aiSignificance: text("ai_significance"),

    publishedAt: timestamp("published_at", { mode: "date" }).notNull(),

    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (article) => ({
    urlIdx: uniqueIndex("news_articles_url_idx").on(article.url),
    assetIdIdx: index("news_articles_asset_id_idx").on(article.assetId),
    impactLevelIdx: index("news_articles_impact_level_idx").on(
      article.impactLevel
    ),
    sentimentIdx: index("news_articles_sentiment_idx").on(article.sentiment),
    publishedAtIdx: index("news_articles_published_at_idx").on(
      article.publishedAt
    ),
  })
);

/**
 * griSnapshots — 15-minute Geopolitical Risk Indicator snapshots.
 * Stores the computed score, bucket, and explanation shown on the GRI dashboard.
 */
export const griSnapshots = pgTable(
  "gri_snapshots",
  {
    id: serial("id").primaryKey(),

    /** Normalised 0–100 risk score */
    score: integer("score").notNull(),
    riskLevel: riskLevelEnum("risk_level").notNull(),

    headlineCount: integer("headline_count").notNull().default(0),

    /** Raw keyword summary from the weighted scan pipeline */
    topKeywords: text("top_keywords"),

    summary: text("summary"),
    marketImpact: text("market_impact"),

    snapshotAt: timestamp("snapshot_at", { mode: "date" }).notNull(),

    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
  },
  (snapshot) => ({
    snapshotAtIdx: uniqueIndex("gri_snapshots_snapshot_at_idx").on(
      snapshot.snapshotAt
    ),
    riskLevelIdx: index("gri_snapshots_risk_level_idx").on(snapshot.riskLevel),
    scoreIdx: index("gri_snapshots_score_idx").on(snapshot.score),
  })
);

/**
 * correlationSnapshots — Daily Pearson correlation outputs for asset pairs.
 * One row per pair per snapshot timestamp.
 */
export const correlationSnapshots = pgTable(
  "correlation_snapshots",
  {
    id: serial("id").primaryKey(),

    // INTEGER — must match assets.id (serial).
    assetId: integer("asset_id")
      .notNull()
      .references(() => assets.id, { onDelete: "cascade" }),

    // INTEGER — must match assets.id (serial).
    relatedAssetId: integer("related_asset_id")
      .notNull()
      .references(() => assets.id, { onDelete: "cascade" }),

    /** Rolling lookback window, e.g. 30-day OHLC */
    windowDays: integer("window_days").notNull().default(30),

    /** Pearson coefficient from -1.0000 to +1.0000 */
    correlationCoefficient: decimal("correlation_coefficient", {
      precision: 6,
      scale: 4,
    }).notNull(),

    strength: correlationStrengthEnum("strength").notNull(),

    /** Optional premium commentary on the relationship */
    aiCommentary: text("ai_commentary"),

    snapshotAt: timestamp("snapshot_at", { mode: "date" }).notNull(),

    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
  },
  (snapshot) => ({
    assetIdIdx: index("correlation_snapshots_asset_id_idx").on(snapshot.assetId),
    relatedAssetIdIdx: index("correlation_snapshots_related_asset_id_idx").on(
      snapshot.relatedAssetId
    ),
    snapshotAtIdx: index("correlation_snapshots_snapshot_at_idx").on(
      snapshot.snapshotAt
    ),
    uniquePairSnapshotIdx: uniqueIndex(
      "correlation_snapshots_pair_snapshot_idx"
    ).on(
      snapshot.assetId,
      snapshot.relatedAssetId,
      snapshot.windowDays,
      snapshot.snapshotAt
    ),
  })
);

/**
 * cbSpeeches — Scheduled and processed central bank speeches.
 * Holds the transcript, final summary, and the dominant decoded tone.
 */
export const cbSpeeches = pgTable(
  "cb_speeches",
  {
    id: serial("id").primaryKey(),

    // INTEGER — must match assets.id (serial).
    assetId: integer("asset_id").references(() => assets.id, {
      onDelete: "set null",
    }),

    institution: cbInstitutionEnum("institution").notNull(),
    speaker: text("speaker").notNull(),
    title: text("title").notNull(),

    youtubeUrl: text("youtube_url").notNull(),

    status: cbSpeechStatusEnum("status").notNull().default("scheduled"),

    scheduledFor: timestamp("scheduled_for", { mode: "date" }).notNull(),
    startedAt: timestamp("started_at", { mode: "date" }),
    endedAt: timestamp("ended_at", { mode: "date" }),

    transcript: text("transcript"),

    /** Final post-speech summary for all authenticated users */
    finalSummary: text("final_summary"),

    dominantTone: speechToneEnum("dominant_tone"),
    confidence: integer("confidence"),

    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (speech) => ({
    youtubeUrlIdx: uniqueIndex("cb_speeches_youtube_url_idx").on(
      speech.youtubeUrl
    ),
    assetIdIdx: index("cb_speeches_asset_id_idx").on(speech.assetId),
    institutionIdx: index("cb_speeches_institution_idx").on(speech.institution),
    statusIdx: index("cb_speeches_status_idx").on(speech.status),
    scheduledForIdx: index("cb_speeches_scheduled_for_idx").on(
      speech.scheduledFor
    ),
  })
);

// ═══════════════════════════════════════════════════════════════════════════════
// §10 — FEATURE RELATIONS
// These relation blocks are append-safe and connect the new tables to the
// existing schema without rewriting the current foundation relations.
// ═══════════════════════════════════════════════════════════════════════════════

export const categoriesRelations = relations(categories, ({ many }) => ({
  prompts: many(prompts),
}));

export const promptsRelations = relations(prompts, ({ one }) => ({
  category: one(categories, {
    fields: [prompts.categoryId],
    references: [categories.id],
  }),
}));

export const economicEventsRelations = relations(
  economicEvents,
  ({ one, many }) => ({
    asset: one(assets, {
      fields: [economicEvents.assetId],
      references: [assets.id],
    }),
    history: many(economicEventHistory),
  })
);

export const economicEventHistoryRelations = relations(
  economicEventHistory,
  ({ one }) => ({
    event: one(economicEvents, {
      fields: [economicEventHistory.eventId],
      references: [economicEvents.id],
    }),
  })
);

export const cotReportsRelations = relations(cotReports, ({ one }) => ({
  asset: one(assets, {
    fields: [cotReports.assetId],
    references: [assets.id],
  }),
}));

export const newsArticlesRelations = relations(newsArticles, ({ one }) => ({
  asset: one(assets, {
    fields: [newsArticles.assetId],
    references: [assets.id],
  }),
}));

export const correlationSnapshotsRelations = relations(
  correlationSnapshots,
  ({ one }) => ({
    asset: one(assets, {
      fields: [correlationSnapshots.assetId],
      references: [assets.id],
      relationName: "correlation_base_asset",
    }),
    relatedAsset: one(assets, {
      fields: [correlationSnapshots.relatedAssetId],
      references: [assets.id],
      relationName: "correlation_related_asset",
    }),
  })
);

export const cbSpeechesRelations = relations(cbSpeeches, ({ one }) => ({
  asset: one(assets, {
    fields: [cbSpeeches.assetId],
    references: [assets.id],
  }),
}));

// ═══════════════════════════════════════════════════════════════════════════════
// §11 — TYPE EXPORTS
// Inferred types for new tables and enums.
// ═══════════════════════════════════════════════════════════════════════════════

export type Category = typeof categories.$inferSelect;
export type NewCategory = typeof categories.$inferInsert;

export type Prompt = typeof prompts.$inferSelect;
export type NewPrompt = typeof prompts.$inferInsert;

export type EconomicEvent = typeof economicEvents.$inferSelect;
export type NewEconomicEvent = typeof economicEvents.$inferInsert;

export type EconomicEventHistory = typeof economicEventHistory.$inferSelect;
export type NewEconomicEventHistory = typeof economicEventHistory.$inferInsert;

export type CotReport = typeof cotReports.$inferSelect;
export type NewCotReport = typeof cotReports.$inferInsert;

export type NewsArticle = typeof newsArticles.$inferSelect;
export type NewNewsArticle = typeof newsArticles.$inferInsert;

export type GriSnapshot = typeof griSnapshots.$inferSelect;
export type NewGriSnapshot = typeof griSnapshots.$inferInsert;

export type CorrelationSnapshot = typeof correlationSnapshots.$inferSelect;
export type NewCorrelationSnapshot = typeof correlationSnapshots.$inferInsert;

export type CbSpeech = typeof cbSpeeches.$inferSelect;
export type NewCbSpeech = typeof cbSpeeches.$inferInsert;

export type ImpactLevel = (typeof impactLevelEnum.enumValues)[number];
export type RiskLevel = (typeof riskLevelEnum.enumValues)[number];
export type NewsSentiment = (typeof newsSentimentEnum.enumValues)[number];
export type PromptScope = (typeof promptScopeEnum.enumValues)[number];
export type CorrelationStrength =
  (typeof correlationStrengthEnum.enumValues)[number];
export type CbInstitution = (typeof cbInstitutionEnum.enumValues)[number];
export type CbSpeechStatus = (typeof cbSpeechStatusEnum.enumValues)[number];
export type SpeechTone = (typeof speechToneEnum.enumValues)[number];
